wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706455854.800214
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 3
      - 13
      - 23
      4: 3.10.4
      5: 0.16.2
      6: 4.34.0
      8:
      - 4
      - 5
      13: darwin-arm64
